### ISSUE TITLE
After update latest.csv only contains status "Not found"

### ISSUE THREAD

**Issue by sbucek** [thenbe/fzf-raindrop#2]
Full content of the latest.csv:

{"result":false,"status":404,"errorMessage":"Not found"}

Downloading https://api.raindrop.io/v1/raindrops/0/export.csv from browser works just fine.

**Comment by thenbe** [comment]
I just tried pulling from the same endpoint and it downloads as expected. That means that this is most likely an auth issue. Can you make sure that `FZF_RAINDROP_COOKIE` environment variable is set. If you're sure that it was set, try updating it as it might have expired (or revoked).

**Comment by thenbe** [comment]
The cookie was probably set, otherwise the program [wouldn't](https://github.com/thenbe/fzf-raindrop/blob/c432acce74f1da9d4e3887001bf7a6848155c8da/fzf-raindrop#L3) have run.

Try updating the cookie with a fresh value.

**Comment by sbucek** [comment]
Got it, thanks I just copied the value, forgot to prepend connect.sid= to the cookie string, Cheers man, cool work!

**Comment by sbucek** [comment]
Gonna close it down.
